AllCops:
  Include:
    - 'Rakefile'
    - 'config.ru'
    - 'Gemfile'
  Exclude:
    - Guardfile
    - bin/**
    - db/**/**
    - scripts/**
    - spec/**/**/**/**
    - test/**/**/**/**
    - tmp/**/**/**/**
    - lib/modules/**/**
Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'Gemfile'

Metrics/MethodLength:
  CountComments: false
  Max: 20

Metrics/AbcSize:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/BlockLength:
  CountComments: false
  Max: 40
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Style/FrozenStringLiteralComment:
  EnforcedStyle: when_needed
